---
title: 'Data Organization'
author: 'Matteo Bellitti' 
---
# Data Organization
All neuro-related datasets are now on SCC.

::: {.callout-important}
# Workstation storage policy changes 
As we migrate all datasets to SCC storage, we will implement a storage restriction on the workstations. A final decision has not been made yet, but every lab member will be allowed ~150GB to discourage dataset duplication while allowing a reasonable amount of working space.
:::

All datasets in the lab should follow the [BIDS standard](https://bids-specification.readthedocs.io/en/stable/index.html) if datatype makes sense (e.g. MRI, PET, but not necessarily tabular data). 

# Read/Write access to datasets on the workstations
By default everyone has read access to the datasets, but to prevent accidents only members of the `dataset-editors` are allowed do write (or delete) from the dataset directory. To check if you are in this group, look at the output of
```
$ groups
```
If you have sudo access and need to add a user to the group, use 
```
$ sudo usermod -aG dataset-editors user
```

