---
title: 'Project Workload Expectations'
author: 'Aubrey Odom' 
---

The Kolachalama Lab is comprised of researchers from many different backgrounds, including postdoctoral fellows, PhD students, MD or MD/PhD students, Master's students, undergraduate researchers, and staff scientists. All lab members are expected to be involved in one or more projects in the lab, although the expectations for workload differ based on the role of the lab member.

# 1. Trainees

For any given trainee, the number of projects with substantial involvement should be limited to no more than three. The goal of this is to ensure that students are not overburdened and that all active projects receive the proper amount of attention and commitment from project members. In all cases, choice of project and workload can be adapted based on individual circumstances, including personal preferences, prior research experience, and/or external circumstances.

Individual cases can be discussed with Dr. Kolachalama as needed.

## 1.1 Undergraduate Students

Undergraduate students may contribute to collaborative projects under the supervision of PhD or Master's students. Their contributions should be reasonably balanced alongside coursework and other obligations. Undergraduate students can expect to be participants on 1-2 projects.

## 1.2 Master's Students

Master's students typically join the lab with the expectation of completing a manageable project under the supervision of a PhD student that they will then use as the basis for their Master's Thesis. This is referred to as their "main" project; they are welcome to take on 1-2 small roles on other projects on collaborative teams.

## 1.3 Medical Students (MD)

MD students are often balancing coursework and clinical training with research responsibilities, and seek to engage with research to pursue non-clinical interests. Depending on their present workload, students may take on collaborative roles on 2-3 projects.

## 1.4 PhD & MD/PhD Students

Students' involvement in the Kolachalama Lab will be a formative part of their research experience and training. 

During their time in the lab, students should aim to write and publish three first-author (or joint first-author) papers by graduation, which will form the backbone of their dissertation work.

Students' workloads are expected to change as they progress through their PhD program. At any given time students should maintain a balanced workload by taking on (1) main project where they focus the majority of their efforts, (1) side project which requires less of their time and focus, and (1) variable item, which may include a teaching assistantship, coursework, applying to jobs, or involvement on an additional project. 

Preparation for qualifying exams and/or dissertation defenses may require pausing work on any or all projects.

# 2. Staff Scientists & Research Assistants (RAs)

Researchers that are neither trainees nor postdocs should communicate with Dr. Kolachalama about projects needing their involvement.

# 3. Postdoctoral Fellows (Postdocs)

Postdocs are seen as near-independent researchers and can be flexible in what responsibilities they take on. They may be expected to be involved in some projects associated with grants that support their salary.
