---
title: 'SCC'
author: 'Matteo Bellitti' 
---

# Using SCC

> "The Boston University [Shared Computing Cluster](https://www.bu.edu/tech/support/research/computing-resources/scc/) (SCC) is a heterogeneous Linux cluster \[...\] suitable for high-performance computing."

To learn how to use SCC, check out [the introductory guides](https://www.bu.edu/tech/support/research/system-usage/) on BU's website.

In practice, you should run your code on SCC if you

1.  Need to access one of the large datasets, and/or
2.  Need a lot of computing power (CPU or GPU)

You should run on the workstations (or your own device)

1.  For quick prototyping
2.  If your analysis is light: if you're using tabular data only or doing a regression analysis it's probably fine.


## Connecting to SCC

The most common ways of connecting to SCC are via SSH or using OnDemand.

1.  SSH: gives you a terminal interface to SCC. Remember that you have to go through `scc4.bu.edu` to access the `restricted` data partitions. For more info, see the [official BU guide](https://www.bu.edu/tech/support/research/system-usage/connect-scc/ssh/).

2.  [SCC OnDemand](https://scc-ondemand.bu.edu/): friendly web based interface. Lets you access the data in your home directory and the lab directory, also lets you run interactive apps (Jupuyter, VSCode, MATLAB, etc.) on SCC via browser. For more info, see the [official BU guide](https://www.bu.edu/tech/support/research/system-usage/connect-scc/scc-ondemand/). Really, give OnDemand a try, it's awesome.

If you use VSCode, you can also connect to SCC using the "Connect to Host" command, which is very convenient for editing your code. Remember: do NOT use the login nodes for any heavy computation, your process will be terminated. When you're ready to run your code, submit it as a [batch job](https://www.bu.edu/tech/support/research/system-usage/running-jobs/submitting-jobs/), request [a shell](https://www.bu.edu/tech/support/research/system-usage/running-jobs/interactive-jobs/), or use the interactive apps on [SCC OnDemand](https://scc-ondemand.bu.edu/).

## Recommended SCC Workflow

::: {.callout-note collapse="false"}
When submitting a job make sure to specify the project name.
The global project name is `vkolagrp`
:::

## Where is my data?